"""
utils.generate_qa_docs
==========================

Generates four of the five QA pages under ``docs/source/qa/`` directly from
``tests/qa/catalogue.toml`` / ``tests/qa/known_gaps.txt`` and a real pytest collection pass, so none
of their numbers are typed by hand:

- ``feature_catalogue.rst`` -- every epic/feature/requirement, in catalogue order.
- ``test_cases.rst`` -- every real test, numbered ``TC-<TYPE>-NNN`` within its layer, plus one
  placeholder row per documented gap (CLAUDE.md SS7: a QA page that only shows shipped work is not
  a real QA artifact).
- ``traceability.rst`` -- one row per requirement: its test cases (by TC id, not raw node id),
  status, and coverage.
- ``coverage_by_feature.rst`` -- requirement coverage rolled up per feature.

Run by hand (no CI in this project, CLAUDE.md SS11's own disclosed gap):
``python -m utils.generate_qa_docs``. The fifth QA page, ``test_results.rst`` (actual pass/fail/
duration from a real run), is generated separately by
:mod:`utils.generate_test_results_rst`, since it needs a junit.xml a real pytest run produced --
this script only ever collects, never runs, tests.
"""

from __future__ import annotations

import pathlib

from utils.check_traceability import CATALOGUE_PATH, KNOWN_GAPS_PATH, load_catalogue, load_known_gaps
from utils.qa_report_lib import (
    TEST_TYPE_ORDER,
    assign_tc_ids,
    build_coverage,
    collect_test_records,
    first_docstring_line,
    render_list_table,
    status_label,
)

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
QA_DOCS_DIR = REPO_ROOT / "docs" / "source" / "qa"

_BANNER = (
    ".. This page is generated by ``python -m utils.generate_qa_docs`` from "
    "``tests/qa/catalogue.toml`` / ``tests/qa/known_gaps.txt`` and a real pytest collection pass. "
    "Do not hand-edit it -- edit the catalogue and regenerate.\n\n"
)


def _requirements_by_feature(catalogue: dict) -> dict[str, list[dict]]:
    """Group the catalogue's requirements under their feature id, in catalogue order."""
    by_feature: dict[str, list[dict]] = {}
    for req in catalogue.get("requirement", []):
        by_feature.setdefault(req["feature"], []).append(req)
    return by_feature


def _feature_names(catalogue: dict) -> dict[str, str]:
    return {f["id"]: f["name"] for f in catalogue.get("feature", [])}


def _epic_names(catalogue: dict) -> dict[str, str]:
    return {e["id"]: e["name"] for e in catalogue.get("epic", [])}


def _feature_epic(catalogue: dict) -> dict[str, str]:
    return {f["id"]: f["epic"] for f in catalogue.get("feature", [])}


def build_feature_catalogue_rst(catalogue: dict) -> str:
    """Render ``feature_catalogue.rst``: one list-table per epic, Feature/Req ID/Requirement/Value."""
    epic_names = _epic_names(catalogue)
    feature_names = _feature_names(catalogue)
    reqs_by_feature = _requirements_by_feature(catalogue)

    features_by_epic: dict[str, list[str]] = {}
    for feature in catalogue.get("feature", []):
        features_by_epic.setdefault(feature["epic"], []).append(feature["id"])

    sections = ["Feature Catalogue", "===================", "", _BANNER.rstrip()]
    for epic in catalogue.get("epic", []):
        sections.append("")
        sections.append(epic_names[epic["id"]])
        sections.append("~" * len(epic_names[epic["id"]]))
        sections.append("")
        rows = []
        for feature_id in features_by_epic.get(epic["id"], []):
            feature_label = feature_names[feature_id]
            for i, req in enumerate(reqs_by_feature.get(feature_id, [])):
                rows.append(
                    [
                        feature_label if i == 0 else "",
                        req["id"],
                        req["text"],
                        req["value"],
                    ]
                )
        sections.append(render_list_table(["Feature", "Req ID", "Requirement", "Value"], rows, [20, 18, 50, 12]))
    return "\n".join(sections) + "\n"


def build_test_cases_rst(catalogue: dict, known_gaps: dict, records: list[dict]) -> str:
    """Render ``test_cases.rst``: one section per test layer, plus a Known Gaps section of placeholders."""
    node_ids_by_type: dict[str, list[str]] = {t: [] for t in TEST_TYPE_ORDER}
    for record in records:
        node_ids_by_type[record["type"]].append(record["node_id"])
    tc_ids = assign_tc_ids(node_ids_by_type)

    req_values = {req["id"]: req["value"] for req in catalogue.get("requirement", [])}

    sections = ["Test Cases", "===========", "", _BANNER.rstrip()]
    for test_type in TEST_TYPE_ORDER:
        type_records = [r for r in records if r["type"] == test_type]
        if not type_records:
            continue
        sections.append("")
        sections.append(test_type)
        sections.append("~" * len(test_type))
        sections.append("")
        rows = []
        for record in type_records:
            req_ids = record["req_ids"]
            prio = req_values.get(req_ids[0], "") if req_ids else ""
            rows.append(
                [
                    tc_ids[record["node_id"]],
                    ", ".join(req_ids) if req_ids else "-",
                    first_docstring_line(record["doc"]),
                    test_type,
                    prio,
                    status_label(is_covered=True, is_xfail=record["is_xfail"]),
                    record["node_id"],
                ]
            )
        sections.append(
            render_list_table(
                ["TC", "Req", "Title", "Type", "Prio", "Status", "Node"],
                rows,
                [10, 14, 36, 10, 8, 14, 30],
            )
        )

    if known_gaps:
        sections.append("")
        sections.append("Known Gaps")
        sections.append("~~~~~~~~~~~")
        sections.append("")
        sections.append(
            "No test exists yet for these requirements; see ``tests/qa/known_gaps.txt`` for why "
            "and what closes each one."
        )
        sections.append("")
        req_text = {req["id"]: req["text"] for req in catalogue.get("requirement", [])}
        rows = [
            ["-", req_id, req_text.get(req_id, ""), "-", req_values.get(req_id, ""), "Not implemented", "-"]
            for req_id in sorted(known_gaps)
        ]
        sections.append(
            render_list_table(
                ["TC", "Req", "Title", "Type", "Prio", "Status", "Node"], rows, [10, 14, 36, 10, 8, 14, 30]
            )
        )
    return "\n".join(sections) + "\n"


def build_traceability_rst(
    catalogue: dict, known_gaps: dict, coverage: dict[str, list[str]], tc_ids: dict[str, str]
) -> str:
    """Render ``traceability.rst``: one row per requirement -- its TC ids, status, coverage."""
    req_ids = sorted(req["id"] for req in catalogue.get("requirement", []))
    covered = {r for r, nodes in coverage.items() if nodes}

    rows = []
    for req_id in req_ids:
        is_covered = req_id in covered
        is_gap = req_id in known_gaps
        tcs = ", ".join(tc_ids.get(n, n) for n in coverage.get(req_id, [])) or "-"
        status = status_label(is_covered=is_covered)
        cov = "Covered" if is_covered else ("Gap" if is_gap else "GAP (undocumented)")
        rows.append([req_id, tcs, status, cov])

    total = len(req_ids)
    covered_count = len(covered)
    header = (
        f"Coverage summary: {covered_count} of {total} requirements have at least one real "
        f"test ({round(100 * covered_count / total) if total else 0}%)."
    )
    return "\n".join(
        [
            "Requirements Traceability",
            "===========================",
            "",
            _BANNER.rstrip(),
            "",
            header,
            "",
            render_list_table(["Requirement", "Test cases", "Status", "Coverage"], rows, [16, 30, 16, 16]),
            "",
        ]
    )


def build_coverage_by_feature_rst(catalogue: dict, coverage: dict[str, list[str]]) -> str:
    """Render ``coverage_by_feature.rst``: per feature, how many of its requirements are covered."""
    feature_names = _feature_names(catalogue)
    feature_epic = _feature_epic(catalogue)
    epic_names = _epic_names(catalogue)
    reqs_by_feature = _requirements_by_feature(catalogue)
    covered = {r for r, nodes in coverage.items() if nodes}

    rows = []
    for feature in catalogue.get("feature", []):
        reqs = reqs_by_feature.get(feature["id"], [])
        n_covered = sum(1 for r in reqs if r["id"] in covered)
        pct = round(100 * n_covered / len(reqs)) if reqs else 0
        rows.append(
            [
                epic_names[feature_epic[feature["id"]]],
                feature_names[feature["id"]],
                f"{n_covered}/{len(reqs)}",
                f"{pct}%",
            ]
        )

    return "\n".join(
        [
            "Coverage by Feature",
            "=====================",
            "",
            _BANNER.rstrip(),
            "",
            "Derived from Feature Catalogue and Requirements Traceability -- this is requirement "
            "coverage (at least one real test per requirement), not code-line coverage. Code "
            "coverage (``pytest-cov``) is reported separately on the Test Results page.",
            "",
            render_list_table(["Epic", "Feature", "Requirements covered", "Coverage"], rows, [20, 24, 16, 12]),
            "",
        ]
    )


def main() -> None:
    catalogue, _ = load_catalogue(CATALOGUE_PATH)
    known_gaps = load_known_gaps(KNOWN_GAPS_PATH)
    records = collect_test_records()
    coverage = build_coverage(records)

    node_ids_by_type: dict[str, list[str]] = {t: [] for t in TEST_TYPE_ORDER}
    for record in records:
        node_ids_by_type[record["type"]].append(record["node_id"])
    tc_ids = assign_tc_ids(node_ids_by_type)

    QA_DOCS_DIR.mkdir(parents=True, exist_ok=True)
    pages = {
        "feature_catalogue.rst": build_feature_catalogue_rst(catalogue),
        "test_cases.rst": build_test_cases_rst(catalogue, known_gaps, records),
        "traceability.rst": build_traceability_rst(catalogue, known_gaps, coverage, tc_ids),
        "coverage_by_feature.rst": build_coverage_by_feature_rst(catalogue, coverage),
    }
    for name, content in pages.items():
        path = QA_DOCS_DIR / name
        path.write_text(content, encoding="utf-8", newline="\n")
        print("wrote", path)


if __name__ == "__main__":
    main()
